apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: default
spec:
  hard:
    limits.cpu: "25m"
    limits.memory: 10Mi
    requests.cpu: "25m"
    requests.memory: 10Mi