apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: web-svr
  name: web-svr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web-svr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: web-svr
    spec:
      containers:
      - image: floridakeys/go-srv:v0.4
        name: web-svr
        resources: 
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
status: {}
